vim:
  edit-commentary:
    git: https://github.com/tpope/vim-commentary.git
  edit-easy_align:
    git: https://github.com/junegunn/vim-easy-align.git
  edit-endwise:
    git: https://github.com/tpope/vim-endwise.git
  edit-rsi:
    git: https://github.com/tpope/vim-rsi.git
  ft-csv:
    git: https://github.com/chrisbra/csv.vim.git
  ft-fish:
    git: https://github.com/aliva/vim-fish.git
  ft-fortune:
    git: https://github.com/ljcooke/vim-fortune.git
  ft-io:
    git: https://github.com/andreimaxim/vim-io.git
  ft-javascript:
    git: https://github.com/pangloss/vim-javascript.git
  ft-ledger:
    git: https://github.com/ledger/vim-ledger
  ft-markdown-github:
    git: https://github.com/rhysd/vim-gfm-syntax.git
  ft-org:
    git: https://github.com/jceb/vim-orgmode.git
  ft-pgn:
    git: https://github.com/artoj/pgn-syntax-vim.git
  ft-qif:
    git: https://github.com/ljcooke/vim-qif.git
  ft-ruby-bundler:
    git: https://github.com/tpope/vim-bundler.git
  ft-toml:
    git: https://github.com/cespare/vim-toml.git
  sensible:
    git: https://github.com/tpope/vim-sensible.git
  ui-lightline:
    git: https://github.com/itchyny/lightline.vim.git
