vim:
  bundler:
    git: https://github.com/tpope/vim-bundler.git
  commentary:
    git: https://github.com/tpope/vim-commentary.git
  csv:
    git: https://github.com/chrisbra/csv.vim.git
  easy-align:
    git: https://github.com/junegunn/vim-easy-align.git
  endwise:
    git: https://github.com/tpope/vim-endwise.git
  fish:
    git: https://github.com/aliva/vim-fish.git
  fortune:
    git: https://github.com/araile/vim-fortune.git
  github-markdown:
    git: https://github.com/rhysd/vim-gfm-syntax.git
  gundo:
    git: https://github.com/sjl/gundo.vim.git
  io:
    git: https://github.com/andreimaxim/vim-io.git
  pgn:
    git: https://github.com/artoj/pgn-syntax-vim.git
  qif:
    git: https://github.com/araile/vim-qif.git
  rsi:
    git: https://github.com/tpope/vim-rsi.git
  sensible:
    git: https://github.com/tpope/vim-sensible.git
  toml:
    git: https://github.com/cespare/vim-toml.git
