csv:        https://github.com/chrisbra/csv.vim.git
easy-align: https://github.com/junegunn/vim-easy-align.git
fish:       https://github.com/aliva/vim-fish.git
fortune:    https://github.com/araile/vim-fortune.git
gundo:      https://github.com/sjl/gundo.vim.git
io:         https://github.com/andreimaxim/vim-io.git
pgn:        https://github.com/artoj/pgn-syntax-vim.git
qif:        https://github.com/araile/vim-qif.git
toml:       https://github.com/cespare/vim-toml.git
